name: React CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checka ut koden
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Installera Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      # 3. Installera beroenden
      - name: Install dependencies
        run: npm install

      # 4. Bygg projektet
      - name: Build
        run: npm run build

      # 5. (Valfritt) Kör tester om du har några
      - name: Run tests
        run: npm test -- --watchAll=false
